version: '2'
services:
  laravel:
    container_name: laravel
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./app/:/var/www/app
    command: 'php artisan serve --host=0.0.0.0'
    ports:
      - 8000:8000
